Document: python-path-and-address
Title: Debian python-path-and-address Manual
Author: <insert document author here>
Abstract: This manual describes what python-path-and-address is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-path-and-address/python-path-and-address.sgml.gz

Format: postscript
Files: /usr/share/doc/python-path-and-address/python-path-and-address.ps.gz

Format: text
Files: /usr/share/doc/python-path-and-address/python-path-and-address.text.gz

Format: HTML
Index: /usr/share/doc/python-path-and-address/html/index.html
Files: /usr/share/doc/python-path-and-address/html/*.html
